### ISSUE TITLE
need to update BV workspace on virtual machines

### ISSUE THREAD

**Issue by val-pf** [ml4ai/tomcat#238]
The virtual machines are reading an old version of the BV workspace. Need to update those.

**Comment by eduongAZ** [comment]
BrainVision Recorder reads out a file with settings every time it's opened, which is called "workspace". This file contains information as to how many electrodes and where they are, what scales to apply, and others. This file has been updated recently on the main windows machine, but not on the virtual machines. It's a pretty low priority item, since the changes were minimal, but it would be important to implement it so that the capping procedure is similar for all three participants.

**Comment by eduongAZ** [comment]
Problem resolved by creating a new USB filter on virtual machine with name "ToMCAT USB". Since only one operating system can read the USB at any time, ejecting the USB on the original Windows allows the USB to be detected by the virtual machines.
