### ISSUE TITLE
Copying over data from iMacs to CAT

### ISSUE THREAD

**Issue by adarshp** [ml4ai/tomcat#292]
Currently, the eye tracker video and Aurora data is written to the iMacs (eye tracker coordinates are streamed to CAT via LSL). 

The data is then transferred to CAT via a manual rsync invocation. We should automate this as part of the uber-script (#287).

We may also look into having the iMacs write the video to CAT directly (via NFS), playing with the resolution, etc. May have option in the uber-script to switch between the methods.

Eye tracker video is currently about 500 MB/minute.

High priority to *start* working on this now, not critical to get it working immediately.

**Comment by chinmaib** [comment]
At today's testing session, we had both eye-tracker Pupil Core recordings and Aurora fNIRS data write to the NFS location on CAT server instead of iMac local storage. We did not notice any lag or delay in any of the other programs.
We will currently keep this setting as this avoids having to rsync data from iMacs to CAT server later on.

Location of recordings on CAT server:
**/User/labworker/data/cat/LangLab/Study3/PupilRecordings**
**/User/labworker/data/cat/LangLab/Study3/AuroraRecordings**

Some issues to be further investigated:
- Aurora had to be force shut after the testing session was completed. Does this have anything to do with writing to NFS location.

**Comment by kobus-barnard** [comment]
Those locations cannot be correct. I see on Tom:
/data/cat/LangLab/Study3/PupilRecordings

However, this is not the organization we want.

**Comment by chinmaib** [comment]
Aurora (fNIRS) NEEDS to write to the local iMac disk in order to function. Additionally, Aurora also streams fNIRS data which is captured by the LSL LabRecorder program and it gets stored in the appropriate location on the CAT server. 
We tried having Aurora write to NFS location instead and it posed problems. Hence, we will keep writing to the local iMac disk. This data saved on the local iMac disk is in a different format from the XDF format captured by LSL. These files are useful for validation and visualization, hence we will keep them (for now). The size of fNIRS data per session is anywhere between 50-100 MB. As a next step, we should write a script which will run on iMacs once a week to archive/backup this data on the servers.

**Comment by paulosoaresua** [comment]
@chinmaib I think it's better to perform the backup in the uber script in the final clean-up step unless I am unaware of a reason not to do that. Then we don't need to worry about running another script weekly.

**Comment by chinmaib** [comment]
Agreed. I think it would be best to handle the final clean-up through the Uber script as well.
