### ISSUE TITLE
ClientMap minimap breaks when starting using UberScript

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat#306]
The minimap shows a a lot of noisy markers, and it does not show player position nor the placed markers.

**Comment by adarshp** [comment]
We will try switching to Google Chrome

**Comment by adarshp** [comment]
Suggestion from Adarsh:

- Use the `port_forwarder` script to forward port 9000 from the iMac to TOM, then access `https://localhost:9000/ClientMap` in Chrome instead of `https://192.168.x.x:9000/ClientMap`

**Comment by kay-of-a** [comment]
The issue we've been having is that Chrome doesn't like the ClientMap certificate. In other OSes, there's a button to proceed anyway. Chrome doesn't have this in mac. 

Workaround: On the error page Chrome gives, type 'thisisunsafe' and Chrome will proceed to the ClientMap. It's a secret code.  You might be able to send the keyboard input programmatically from the uberscript.

**Comment by adarshp** [comment]
@kay-of-a - did you try the port forwarding method?

**Comment by kay-of-a** [comment]
I did not. I can try that tomorrow as well, but typing 'thisisunsafe' also seems to work, unless I'm missing something.

**Comment by adarshp** [comment]
It works, but my guess is that it will be harder to programmatically send keyboard input than to start port forwarding.

**Comment by kay-of-a** [comment]
I just used the port_forwarder script to open clientMap on Lion. It worked, but I had to change some things on Lion. 

- The port_forwarder script's shebang references python2 but the script uses python3 features (fstrings). I ran it with python3.
- Tom's IP was incorrect in Lion's .ssh/config (.23 at the end instead of 24) I changed it to the correct IP. 
- Initially the ssh failed. I used ssh-add -l and found that Lion's ssh didn't know about the private key for tomcat that was already in .ssh I used ssh-add to add the key.

If this sounds reasonable, I'll make the same changes to /.ssh/config and add the private key on the other Macs and test it in the next dry run.

**Comment by adarshp** [comment]
> I just used the port_forwarder script to open clientMap on Lion. It worked, but I had to change some things on Lion.
> 
> * The port_forwarder script's shebang references python2 but the script uses python3 features (fstrings). I ran it with python3.

The shebang references python, not python2. If python 3 is the active python (e.g., if you have a python3 virtual environment or you configure it with MacPorts as described [here](https://adarsh.cc/posts/macports_python.html) then it should work fine

> * Tom's IP was incorrect in Lion's .ssh/config (.23 at the end instead of 24) I changed it to the correct IP.

Thank you!

> * Initially the ssh failed to authenticate. I used ssh-add -l and found that Lion's ssh didn't know about the private key for tomcat that was already in .ssh. I used ssh-add to add the key.
> 
> If this sounds reasonable, I'll make the same changes to /.ssh/config and add the private key on the other Macs and test it in the next dry run.

This does sound reasonable - thanks!

**Comment by adarshp** [comment]
Update: @paulosoaresua is going to look into this more and see if it works robustly - and if so, incorporate the port forwarding into the UberScript.
