### ISSUE TITLE
Investigate validity of Aurora data recorded by LSL when Aurora is paused-unpaused

### ISSUE THREAD

**Issue by CalebUAz** [ml4ai/tomcat#307]

**Comment by CalebUAz** [comment]
For 04-29-2022 testing we decided to pause between tasks and plot for timestamps looks something like this:
![Untitled Diagram drawio-2](https://user-images.githubusercontent.com/90938130/166085243-00baf1cb-b9b1-4614-9a56-88967df0feac.png)

1. We hit record on labrecorder.
2. We stop recording on Aurora. 
3. We start the recording again on Aurora. 
4. We stop recording on Aurora. 
5. We start the recording again on Aurora. 
6. We stop recording on Aurora. 

When we did this **Aurora didn't crash** also Labrecorder picks up the fNIRS signals where we last left it. 

At LSL index 16613 we stopped aurora recording and next index we resumed recording:
![image](https://user-images.githubusercontent.com/90938130/166085651-e491adcb-ca3c-445a-80a9-f1fe465bcbb8.png)

**Comment by eduongAZ** [comment]
I am confused looking at the Relative Time from Aurora vs. Timestamp from LSL plot. What I get from the plot is that Relative Time from Aurora was reset back to zero every time Aurora was paused-unpaused. I expect there to be a gap of nothingness in Timestamp from LSL as well, because LSL should not be recording any Aurora data when Aurora was paused.

This plot does not convince me that LSL was correctly recording Aurora data when Aurora is paused-unpaused.

**Comment by CalebUAz** [comment]
Maybe LSL wasn't implemented that way to take care of "Nothingness". I mean even if LSL places NANs or NULLs in the streams we'd probably remove it during post processing.

**Comment by eduongAZ** [comment]
Can you read from all NIRx files and plot a data vs. the timestamp? I want to make sure that Aurora does not simply write over old data. When you read and plot from all NIRx files, I expect there to be a gap on the plot where there is no data.

**Comment by CalebUAz** [comment]
Are you talking about NIRx files that is locally stored in aurora? Or What is streamed through LSL? 

This plot shows filtered HbO channel 1 vs timestamp from LSL:
![image](https://user-images.githubusercontent.com/90938130/167017113-1d0e2e50-4ce5-4765-b8e0-3b0675951488.png)

Its not overwriting the existing data collected by LSL in the XDF file, it if was overwriting on existing data then you see an upwards plot from zero not a zig zag plot:
![](https://user-images.githubusercontent.com/90938130/166085243-00baf1cb-b9b1-4614-9a56-88967df0feac.png)

@chinmaib do you concur with what I'm saying?

**Comment by eduongAZ** [comment]
I expect the "Relative time from Aurora" to keep going upward if we don't pause Aurora. However, all the plot is saying is that the Relative time from Aurora was reset to zero, which could also indicate Aurora is writing from scratch, or it could mean many things, and we don't know what those many things are. 

Even when Aurora is paused, I expect the "Relative time from Aurora" to keep going up anyway (not zig zag) because it should know that the experiment is still going and the time should be relative to when LabRecorder first records. It seems that the time is relative to when Aurora was last unpaused, not when LabRecorder first records.

Furthermore, if you look at HbO plot, the data is continuous. There is no indication of pausing. My question is: where did the data come from when Aurora was paused?

**Comment by CalebUAz** [comment]
We aren't **pausing** aurora rather we are **stopping and starting** it again which means its creating a new file on the local machine but resumes streaming onto LSL whenever we hit record. 

We stopped at `12:21` after baseline. 
Started it back at `12:38 `for Minecraft Saturn A. 
Stopped it at `12:56`. 
Started it back at `12:59` for Minecraft Saturn B. 
Finished up with everything at `1:37`. 

I observed another discrepancy:
![image](https://user-images.githubusercontent.com/90938130/167036946-7a0819cd-6421-482e-8820-d256e70e02f5.png)
The first sheet is fNIRS, 2nd is EEG and 3rd is Pupil capture. All have the same timestamp, which means LSL doesn't stop the time stamp even though one of the streams isn't coming in. 

We ran the entire dry run from `11:54AM` to `1:37PM `which is `1hr 42mins (i.e. 6165 sec)`, fNIRS has a sampling rate of ~10 hz so we should get 61650 samples. 

But number of samples in the XDF file for fNIRS is 49,456 which means when we paused the stream there wasn't anything coming in.

**Comment by chinmaib** [comment]
Looks like Aurora and LSL are behaving just the way we expect. I agree with Caleb, that LSL is picking up streams after we stop and start Aurora automatically.
We still need to check if the same behavior happens when Aurora crashes and we restart the entire program.

**Comment by chinmaib** [comment]
For visualization, the plot of **HbO channel 1 vs timestamp from LSL** is confusing. Are timestamps from LSL absolute times? The zigzag plot with absolute timestamps from LSL vs relative aurora times is also confusing.

Ideally, a plot of HbO channel 1 vs (absolute) timestamps from LSL should show gaps, but @eduongAZ since there is no data being streamed, nothing is written to the XDF file. Hence we do not see any gaps in the plot 3. But associated timestamps are accurate.

**Comment by eduongAZ** [comment]
What's the status on this issue? We need to resolve this soon to decide whether to buy new computers, which tend to take a while to be delivered.

**Comment by adarshp** [comment]
@CalebUAz  - could you please add an explanation for why the issue was closed?

**Comment by adarshp** [comment]
@CalebUAz  - makes sense, thanks!
