### ISSUE TITLE
An API/Interface to extract .metadata files from the testbed

### ISSUE THREAD

**Issue by chinmaib** [ml4ai/tomcat#311]
We want to extract the .metadata files from the testbed after the experiment and save the files on the CAT server. We want to extract these files automatically through scripts and avoid going through the web interface.

**Comment by chinmaib** [comment]
As discussed, we should try reading data from the message bus in real-time.
mosquitto_sub -t "#" > output.metadata

**Comment by adarshp** [comment]
While the one-liner is aesthetically pleasing, realistically we will want a bit more. At a minimum, we will want to record two things: the message topic (key: `topic`), and the timestamp for when the message was received (with the `@timestamp` key to make it compatible with TA3 testbed exports and replay tools).

The plan is for @paulosoaresua to make a simple Python MQTT client program using the paho-mqtt Python package  - this program will deal with the recording and writing of the messages to a file.

@paulosoaresua  - Instead of doing `json.dump(message, f)`, I suggest doing `f.write(json.dumps(message)+"\n")` (where f is a file handle returned by doing `with open("output.metadata") as f:` or something similar, and `message` is a dict created by feeding the incoming message into `json.loads`. This will ensure that incomplete JSON objects are not written to the file (I just dealt with this issue today in the elkless_replayer script)

**Comment by paulosoaresua** [comment]
The script works but a lot of messages are being generated even for a trial that finishes quickly. This was confirmed by looking at the messages at Kibana. The culprit seems to be the AC_CORNELL_TA2_ASI-FACEWORK that keeps publishing even after the trial stops.
