### ISSUE TITLE
Find way to stop Minecraft from auto updating its version.

### ISSUE THREAD

**Issue by rchamplin** [ml4ai/tomcat#344]
Research and find way to keep Minecraft from downloading and updating its latest version. We want to have Minecraft not auto update to it latest version unless we manually initiate the update process.

**Comment by vincentraymond-ua** [comment]
I looked into this briefly and have a potential solution. From what I've read, its not guaranteed to work for every project, but is a good place to start. First, on a fresh clone of the Tomcat repository install and launch the Malmo Minecraft client using:
1. Run tools/install
2. Run tools/launch_minecraft

This will install and cache the needed dependencies. Next, we can tell Gradle to build using the cached dependencies instead of pulling them from the internet using the `--offline` command line option. To do this, change line 72 in tomcat/external/malmo/Minecraft/launchClient.sh from `./gradlew build` to `./gradlew build --offline`

After this, you should be able to run tools/launch_minecraft without needing to be connected to the internet.

**Comment by vincentraymond-ua** [comment]
Okay perfect, that's probably a slightly simpler solution then.

I'm not as familiar with Gradle, so I was unsure if those lines were needed to be run every time the client is launched.

**Comment by adarshp** [comment]
The relevant lines are now commented out, closing the issue.
