### ISSUE TITLE
Labrecorder isn't picking up any of the data transmissions

### ISSUE THREAD

**Issue by CalebUAz** [ml4ai/tomcat#377]
I am able to ping iMacs (lion & tiger) with Tom & Cat and vice-versa but Labrecorder doesn't pick up any of the physio data coming in from iMacs. 

I tried to run the following python script:
```
from pylsl import StreamInlet, resolve_stream
sample = resolve_stream('type', 'NIRS')
```
This is supposed to give me device id in Hexadecimal, but it in this case its waiting to receive something. 

Not sure if the mounting/unmounting caused this issue. 

Also tried running Labrecorder on Tom and no luck there as well!

**Comment by CalebUAz** [comment]
@chinmaib Eric mentioned you encountered this problem before, do you mind sharing what you did to solve this issue?

**Comment by chinmaib** [comment]
@CalebUAz you have to add the IP addresses of iMacs to the config file for it to pick up streams from iMacs.
Here is a link to the document. 
https://docs.google.com/document/d/1y-AVGpYc8beLalI7o_S3kjw0Xj9lBUsuNdKNXxuWjAA/edit?usp=sharing
I believe you have to complete Step 4. Let me know if this helps.

**Comment by rchamplin** [comment]
Chinmai zoomed with us and help us locate the problem. The problem was that after we did cleanup and remounting of CAT's data drive, the lsl_api could not find its config file lsl_api.cfg. Also, "KnownPeers = {192.168.0.19, 192.168.0.20, 192.168.0.21, 192.168.0.22, 192.168.0.30}" needed to be added to config file. LabRecorder is now seeing LSL streams OK.
